apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: blog
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: minio.local    # thay bằng domain thật hoặc thêm vào /etc/hosts
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9001
