apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blog-app.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blog-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.minioAccessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.minioSecretKey | quote }}
