loki:
  nodeSelector:
    node-role.kubernetes.io/worker: ""

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi

  config:
    limits_config:
      retention_period: 168h
      ingestion_rate_mb: 30
      ingestion_burst_size_mb: 60
      per_stream_rate_limit: 20MB
      per_stream_rate_limit_burst: 40MB

promtail:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

  config:
    clients:
      - url: http://loki-stack:3100/loki/api/v1/push
    snippets:
      scrapeConfigs: |
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          pipeline_stages:
            - docker: {}
          relabel_configs:
            - source_labels: [__meta_kubernetes_namespace]
              regex: blog|monitoring|windgo
              action: keep
            - source_labels: [__meta_kubernetes_pod_label_app]
              target_label: app
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container
