server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki-local:3100/loki/api/v1/push

scrape_configs:
  # Local blog-app log — chỉ dùng khi test local, EC2 tự push qua Tailscale
  - job_name: blog-app
    static_configs:
      - targets: [localhost]
        labels:
          job: blog-app
          service_name: blog-app
          host: local
          __path__: /app/logs/blog-app.log
